config/routes.rb
Rails.application.routes.draw do
  # resources - generate all routes for the controller resources :controller
  # custom route - get 'where it is going' - get 'controller#action'
  # root 'controller#action' the main/ root page , localhost:3000 /
  root 'subs#index'
 
resources :subs do
  resources :topic

  
    # get '/subs', to: 'subs#index'
    # get '/subs/:id', to: 'subs#show'
    # get '/subs/:', to: 'subs#edit'
    # post '/subs', to: 'subs#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics, dependent: :destroy
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  # M odel - All the logic on the table or record, database 
  # restriants, assocations
  # V iew - user interaction, front end, keep logic to a min
  # C ontrollers / routes - direct traffic, actions - what 
  # you can do on the webpage
              #  HTTP VERBS
  # C create -> POST
  # R read -> GET
  # U update -> PUT / PATCH
  # D destroy -> DELETE
  # All Actions Must return a response
    # HTML XML JSON or redirect to an action that does
    # HTML by Default , html page of the action name action.html.erb
  
  # Callbacks - perform logic at certain actions 
  # before_action
  # after_action
  # skip_before_action
  # skip_after_action
  # before_action :method_to_call - all method
                                  # except:
  # before_action :method_to_call, only: [:index, :show, :new]
  # Partials are common / shared views 
  # READ - GET 
    # Page will see and interact with
    # shows record from the db onto the pages
    # index action - see all of the record for the table
      # @model_names = Model_name.all
      # gets all the records and set them to a variable
    # show action - see a single record, id 
      # @model_name = Model_name.find(params[:id])
    # new action - display the new record form, creates the 
    # record in memory
      # @model_name = Model_name.new
    # edit action - displays the edit record form, id
      # @model_name = Model_name.find(params[:id])
  # Create / POST 
    # - create action create a record, from the new action 
    # @model_name = Model_name.new(model_name_params)
    # if @model_name.save
    #   do something
    # else
    #   render :new
    # end
  # UPDATE / PUT PATCH
    # - update action, edit a record, edit form , id 
    #   @model_name = Model_name.find(params[:id])
    #   if @model_name.update(model_name_params)
    #     do something
    #   else
    #     render :edit
    #   end
  # Destroy / DELETE
    # - destroy action delete a record, id 
    
    # Model_name.find(params[:id]).destroy
    # do something
# model_name_params
    # - pass certain attr 
  # private 
  #   def model_name_params
  #     params.require(:model_name).permit(:attr, :everything that table has)
  #   end
  
  # index action - see all of the record for the table
    # @model_names = Model_name.all
    # gets all the records and set them to a variable
  def index
    @subs = Sub.all
  end
  # show action - see a single record, id 
    # @model_name = Model_name.find(params[:id])
  def show
    @sub = Sub.find(params[:id])
  end
  # new action - display the new record form, creates the 
    # record in memory
      # @model_name = Model_name.new
  def new
    @sub = Sub.new
  end
  # Create / POST 
    # - create action create a record, from the new action 
    
    # @model_name = Model_name.new(model_name_params)
    # if @model_name.save
    #   do something
    # else
    #   render :new
    # end
  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to subs_path 
    else
      render :new 
    end
  end
  # edit action - displays the edit record form, id
    # @model_name = Model_name.find(params[:id])
  def edit
    @sub = Sub.find(params[:id])
  end
  # UPDATE / PUT PATCH
    # - update action, edit a record, edit form , id 
    #   @model_name = Model_name.find(params[:id])
    #   if @model_name.update(model_name_params)
    #     do something
    #   else
    #     render :edit
    #   end
  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update(sub_params)
      redirect_to subs_path
    else
      render :edit
    end
  end
  # Destroy / DELETE
  # - destroy action delete a record, id 
  
  # Model_name.find(params[:id]).destroy
  # do something
  def destroy
    Sub.find(params[:id]).destroy
    redirect_to subs_path
  end
  # model_name_params
    # - pass certain attr 
  # private 
  #   def model_name_params
  #     params.require(:model_name).permit(:attr, :everything that table has)
  #   end
  private 
    def sub_params
      params.require(:sub).permit(:name)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_sub 
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    # @topics = Topic.all
              # parent.model_name(s)
    @topics = @sub.topics
  end

  def show
    # @topic = Topic.find(params[:id])
  end

  def new
    # @topic = Topic.new
    @topic = @sub.topics.new
    render partial: 'form'
  end

  def create
    # @topic = Topic.new(topic_params)
    @topic = @sub.topics.new(topic_params)

    if @topic.save
      redirect_to [@sub, @topic]
    else  
      render :new
    end
  end

  def edit
    # @topic = Topic.find(params[:id])
    render partial: 'form'
  end

  def update
    # @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      redirect_to [@sub, @topic]
    else
      render :edit
    end
  end

  def destroy
    # Topic.find(params[:id]).destroy
    @topic.destroy
    redirect_to sub_topics_path
  end

  private
    def topic_params
      params.require(:topic).permit(:name, :body)
    end

    def set_sub
      @sub = Sub.find(params[:sub_id])
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @sub.id ? 'Edit Sub' : 'Create Sub' %></h1>

<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1> All Subs </h1>
<%= link_to 'Create new Sub', new_sub_path %>

<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.name, sub %></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>

<p>What do you like to do?<p>
                                    <!-- @sub.id -->
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<%= link_to 'Edit sub', edit_sub_path(@sub) %>
<%= link_to 'Delete Sub', @sub, method: :delete %>

app/views/topics/_form.html.erb
<h1><%= @topic.id ? 'Edit Topic' : 'Create Topic' %></h1>
<hr />
<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>All of the topics for <%= @sub.name %></h1>

<%= link_to 'Create Topic', new_sub_topic_path(@sub) %>

<ul>
  <% @topics.each do |topic| %>
   <li><%= link_to topic.name, [@sub, @topic] %></li>
  <% end %>
</ul>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1><%= @sub.name %> - <%= @topic.name %></h1>
<p><%= @topic.body %></p>
<%= link_to 'Edit Topic', edit_sub_topic_path([@sub, @topic]) %>
<%= link_to 'Delete Topic', [@sub, @topic], method: :delete %>
<%= link_to 'Back To Topics', sub_topics_path(@sub) %>